name: Github Pages Deploy

on: push

jobs:
  deploy:
    name: Deploy site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: abort on errors
        run: set -e
      
      - name: Install dependencies
        run: npm install

      - name: build
        run: npm run build
      
      - name: navigate to build output directory
        run: cd dist
      
      - name: create a deploy repository
        run: git init && git add -A && git commit -m 'deploy'