name: Github Pages Deploy

on: push

jobs:
  deploy:
    name: Deploy site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: abort on errors
        run: set -e
      
      - name: Install vue cli
        run: npm install -g @vue/cli

      - name: build
        run: npm run build && cd dist